### ISSUE TITLE
Sync problem with strava

### ISSUE THREAD

**Issue by ducvinh9** [Decathlon/hub-decathlon#109]
Hi, my activity (running) on DecathlonCoach do not sync with Strava from yesterday. The error is systematic since my friend had the same problem at the same time. Sync manually on web do not work.

**Comment by canssens** [comment]
Hello @ducvinh9 , thank you for this report.
Could you send me your HUB ID by email : infra@decathloncoach.com ?
You could get this ID, after login onto https://hub.decathlon.com at the bottom of the webpage.

**Comment by ducvinh9** [comment]
My HUB ID is 607fe5fffa8139000905ef8c

**Comment by canssens** [comment]
Ok , we corrected a bug in our fit format, did you get your activity ?

**Comment by ducvinh9** [comment]
I got it. Thank you all for your quick fix.

Sincere,
