### ISSUE TITLE
Fitbit Disconnecting Errors

### ISSUE THREAD

**Issue by kimmccann** [Decathlon/hub-decathlon#38]
Trying to disconnect a fitbit gives 500 internal server errors when hitting the endpoint 'https://hub.decathlon.com/auth/disconnect-do/fitbit'. I've managed to disconnect the fitbit by revoking access in fitbit but it is still showing as connected in the the hub and I can't disconnect it due to errors. Hoping to fix this so I can reconnect it please.

**Comment by canssens** [comment]
Hello, thank you for this feedback,
we are going to patch this issue.

You can communicate your id (at the bottom of the webpage, so i could force unlink), my email : charles.anssens@decathlon.com

**Comment by kevforget** [comment]
Hello,

This PR should resolve this issue. 
You will be able to disconnect the Fitbit services from the HUB and then reconnect.
It should be put into production ASAP
https://github.com/Decathlon/hub-decathlon/pull/40

Again thanks for your feedback.
