### ISSUE TITLE
Garmin integration might be broken

### ISSUE THREAD

**Issue by fecnek** [Decathlon/hub-decathlon#43]
After the authentication with Garmin and agreeing on the Terms&Conditions I'm facing the following error message:
![image](https://user-images.githubusercontent.com/2789840/106713674-1648d280-65fb-11eb-9605-c7f037c06f95.png)

I've done all the described activities (logout/login again, using different browsers and even devices) but without any success.

**Comment by aalse** [comment]
I have a slightly different issue where it shows connected on both Decathlon hub and the Garmin Connect app but no activities are being pushed. The hub only shows me sucessful pushes to Strava.

**Comment by canssens** [comment]
Hello @fecnek , we rewrited all our implementation of login with Garmin, so this bug should not happen now.

Hello @aalse , Garmin only support outbound, so we could retrieve activities, but not send activities to Garmin.

Regards
