### ISSUE TITLE
Impossible de synchroniser avec Strava

### ISSUE THREAD

**Issue by ferryjul** [Decathlon/hub-decathlon#74]
Depuis plus de trois jours, mes activités Strava n'étaient plus synchronisées avec Decathlon Connect (et inversement). C'est Décathlon Hub qui, normalement, s'occupe de cette synchronisation. Sur le détail des synchronisations de decathlonhub ("Voir tout"), une erreur de logins Strava apparait (je n'ai pas modifié mes logins et je n'ai aucun souci avec Strava). Je décide donc de déconnecter Strava de Décathlon Hub, pour le reconnecter. Sauf qu'il m'a été impossible de le reconnecter car Strava n'apparaît plus sur la liste des "Services Disponibles" - et à l'heure actuelle les "Services Disponibles" sont DECATHLON, POLAR FLOW, FITBIT, GARMIN HEALTH et COROS (mais pas Strava, donc)...

**Comment by canssens** [comment]
Bonjour,

C'est un bug que nous n'avons pas encore identifié.
Pouvez vous ressayer et me dire si c'est corrigé?

Sinon pouvez vous vous connecter sur https://hub.decathlon.com, vous loguer, puis me communiquer votre ID (en bas de page) à l'adresse infra@decathloncoach.com .

Merci

**Comment by ferryjul** [comment]
Bonjour,

Le problème est effectivement résolu.

Merci pour votre réactivité!
